# Generated by Django 4.2.4 on 2023-08-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='tutors',
            field=models.ManyToManyField(default='Not Identified', to='school.tutor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='New Course'),
        ),
    ]
