# Generated by Django 4.2.4 on 2023-08-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_course_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='DataIdea', max_length=122)),
                ('url', models.CharField(default='dataidea.com', max_length=122)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ManyToManyField(to='school.organization'),
        ),
    ]
