# Generated by Django 4.2.4 on 2023-08-26 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_organization_course_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='organization',
        ),
        migrations.AddField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.organization'),
        ),
    ]
