# Generated by Django 4.2.4 on 2023-08-28 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_course_image_alter_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.CharField(default='No URLs provided attached', max_length=122),
        ),
    ]
