# Generated by Django 4.2.4 on 2023-08-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_videolink_course_video_links'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_links',
        ),
        migrations.RemoveField(
            model_name='video',
            name='course',
        ),
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(default='No Videos', to='school.video'),
        ),
        migrations.DeleteModel(
            name='VideoLink',
        ),
    ]
