# Generated by Django 4.2.4 on 2023-09-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_remove_course_video_links_remove_video_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='gist',
            field=models.TextField(default='New Gist'),
        ),
    ]
