# Generated by Django 4.2.4 on 2023-09-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_video_gist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='gist',
            field=models.CharField(default='New Gist', max_length=122),
        ),
    ]
