# Generated by Django 4.2.4 on 2023-09-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_remove_comment_course_comment_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='comments',
        ),
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.ManyToManyField(default=1, to='school.comment'),
        ),
    ]
