# Generated by Django 4.2.4 on 2023-09-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
