# Generated by Django 4.2.4 on 2023-09-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_note_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.ManyToManyField(default=12, to='school.comment'),
        ),
    ]
