# Generated by Django 4.2.4 on 2023-09-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_alter_video_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='comments',
            field=models.ManyToManyField(default=None, to='school.comment'),
        ),
    ]
