# Generated by Django 4.2.4 on 2023-09-29 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_remove_question_answer_remove_question_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='quiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.quiz'),
        ),
    ]
