# Generated by Django 4.2.4 on 2023-09-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('dateCreated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(editable=False, max_length=122)),
                ('title', models.CharField(max_length=122)),
                ('brief', models.TextField(default='')),
                ('coverImage', models.TextField(default='')),
                ('dateUpdated', models.DateTimeField(auto_now=True)),
                ('dateFeatured', models.DateTimeField(auto_now=True)),
                ('contentMarkdown', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Hashnode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('blogs_number', models.IntegerField(default=0)),
                ('pages_numeber', models.IntegerField(default=0)),
            ],
        ),
    ]
