# Generated by Django 4.2.4 on 2023-09-05 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.authors'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='email',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='authors',
            name='name',
            field=models.CharField(default='dataidea', max_length=122),
        ),
        migrations.AlterField(
            model_name='blog',
            name='_id',
            field=models.CharField(editable=False, max_length=122, unique=True),
        ),
    ]
