# Generated by Django 4.2.4 on 2023-09-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blog_cover_image_alter_blog_date_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date_featured',
            field=models.CharField(default='', max_length=122, null=True),
        ),
    ]
