# Generated by Django 4.2.4 on 2023-10-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blog_cover_image_alter_blog_date_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='dataidea', max_length=122)),
                ('email', models.CharField(default='datasideaofficial@gmail.com', max_length=122)),
                ('profile', models.CharField(default='No profile provided', max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New category', max_length=122)),
                ('description', models.CharField(default='New category description', max_length=122)),
                ('color', models.CharField(default='purple', max_length=122)),
            ],
        ),
        migrations.DeleteModel(
            name='Authors',
        ),
    ]
