# Generated by Django 4.2.4 on 2023-08-21 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='contact', max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('contact', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='layer', max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FrequentlyAskedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=122)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('image', models.ImageField(upload_to='portfolio')),
                ('category', models.CharField(choices=[('web', 'Web'), ('other', 'Other'), ('tutorial', 'Tutorial')], max_length=8)),
                ('client', models.CharField(default='Private', max_length=50)),
                ('url', models.CharField(default='No url', max_length=100)),
                ('date', models.DateField(null=True)),
                ('description', models.TextField(default='No description')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='layer', max_length=122)),
                ('name', models.CharField(max_length=122)),
                ('image', models.ImageField(default='services/service.html', upload_to='services')),
                ('description', models.TextField(default='One of our services')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Company statistics', max_length=122)),
                ('clients', models.IntegerField(default=5)),
                ('projects', models.IntegerField(default=5)),
                ('workers', models.IntegerField(default=5)),
                ('hours_of_support', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('image', models.ImageField(upload_to='testimonials')),
                ('position', models.CharField(max_length=122)),
                ('testimony', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('price', models.CharField(max_length=122)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.service')),
            ],
        ),
    ]
