# Generated by Django 4.2.4 on 2023-08-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FAQ',
            new_name='FrequentlyAskedQuestion',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='client',
            field=models.CharField(default='Private', max_length=50),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='project_url',
            field=models.CharField(default='No url', max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default='No description'),
        ),
    ]
