# Generated by Django 4.2.4 on 2023-08-21 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
