# Generated by Django 4.2.4 on 2023-08-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_rename_faq_frequentlyaskedquestion_portfolio_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='project_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='portfolio',
            old_name='project_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('web', 'Web'), ('other', 'Other'), ('tutorial', 'Tutorial')], max_length=8),
        ),
    ]
