# Generated by Django 4.2.4 on 2023-08-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_remove_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='color',
            field=models.CharField(default='#f5f5f5', max_length=22),
        ),
    ]
