# Generated by Django 4.2.4 on 2023-10-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_files/')),
                ('transcription_text', models.TextField(blank=True)),
                ('summary_text', models.TextField(blank=True)),
            ],
        ),
    ]
